esphome:
  name: ${device_name}

esp32:
  board: esp32dev

text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version

logger:
  baud_rate: 0
  level: DEBUG
  logs:
    sensor: WARN
    resistance: WARN
    text_sensor: WARN
    ntc: WARN

binary_sensor:
  # Is the device connected
  - platform: status
    name: "${device_name} status"