## Requires ${device_name}, ${api_password} and ${ota_password} to be set.

esphome:
  name: ${device_name}

esp32:
  board: esp32dev

ota:
  password: ${ota_password}

text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version

packages:
  logger: github://e-noyau/esphome/logger.yaml@main
