## Requires ${device_name} and ${ota_password} to be set.

esphome:
  name: ${device_name}

esp32:
  board: esp32dev

logger:
  baud_rate: 0
  level: DEBUG
  logs:
    sensor: WARN
    resistance: WARN
    text_sensor: WARN
    ntc: WARN
    
ota:
  password: ${ota_password}

text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version
