## Requires ${device_name}, ${api_password} and ${ota_password} to be set.

esphome:
  name: ${device_name}

ota:
  - platform: esphome
    password: ${ota_password}

text_sensor:
  - platform: version
    name: ${device_name} ESPHome Version

packages:
  logger: github://e-noyau/esphome/logger.yaml@main

button:
  - platform: restart
    id: restart_button
    icon: mdi:restart
    name: "${device_name} Restart"
    entity_category: config
