## Configures a barebone Sonoff NSPanel
##
## Requires the following substitutions to be set:
##
## • ${device_name}
## • ${wifi_ssid}
## • ${wifi_password}
## • {api_password}
## • ${ota_password}
## • ${uart_speed}, which should match the one in the hmi/tft file.
## • ${tft_url}, where the tft file can be downloaded from.
##

packages:
  board: github://e-noyau/esphome/board_esp32dev.yaml@main
  common: github://e-noyau/esphome/common.yaml@main
  wifi: github://e-noyau/esphome/wifi_bare.yaml@main

external_components:
  # The Nextion display is setup in is in a funky Protocol Reparse Mode, this switches it to a
  # regular mode. 
  # https://github.com/esphome/esphome/pull/2956
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h

api:
  password: ${api_password}
  services:
  - service: upload_tft
    then:
      - lambda: 'id(nextion_display)->upload_tft();'

binary_sensor:
  # The left physical button
  - platform: gpio
    id: left_button
    name: "${device_name} left button"
    pin:
      number: 14
      inverted: true
    icon: mdi:light-switch
    on_press:
      - switch.toggle: relay_1

  # The right physical button
  - platform: gpio
    id: right_button
    name: "${device_name} right button"
    pin:
      number: 27
      inverted: true
    icon: mdi:light-switch
    on_press:
      - switch.toggle: relay_2

output:
  # There is a buzzer on this thing
  - platform: ledc
    id: buzzer_out
    pin:
      number: 21

switch:
  # First relay
  - platform: gpio
    id: relay_1
    name: ${device_name} relay 1
    pin:
      number: 22
    icon: mdi:electric-switch

  # Second relay
  - platform: gpio
    id: relay_2
    name: ${device_name} relay 2
    pin:
      number: 19
    icon: mdi:electric-switch

  # Turn screen power on/off. Easy way to configure the screen power control, but this should not
  # be used from HA, as all components must be re-initialized afterwards.
  - platform: gpio
    id: screen_power
    name: ${device_name} screen power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
    icon: mdi:television

sensor:
  # The temperature sensor. This fluctuates quite a bit, it may need some damping.
  # Really, three entities for the temp?
  - platform: adc # Analog to Digital
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  - platform: ntc # Thermistor
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: "${device_name} temperature"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1

uart:
  id: tf_uart
  tx_pin: 16
  rx_pin: 17
  baud_rate: ${uart_speed} # Either 9600 or 115200

display:
  - platform: nextion
    id: nextion_display
    uart_id: tf_uart
    tft_url: ${tft_url}
