## Requires ${device_name}, ${wifi_ssid} and ${wifi_password} to be set.

packages:
  wifi: github://e-noyau/esphome/wifi.yaml@main
  bt_tracker: github://e-noyau/esphome/bt_tracker.yaml@main
  ns_panel_bare: github://e-noyau/esphome/ns_panel_bare.yaml@main
  uptime: github://e-noyau/esphome/uptime.yaml@main


# Playing buzzer music
rtttl:
  id: buzzer
  output: buzzer_out

binary_sensor:
  # The left physical button
  - platform: gpio
    id: left_button
    name: "${device_name} left button"
    pin:
      number: 14
      inverted: true
    icon: mdi:light-switch
    on_press:
      - switch.toggle: relay_1

  # The right physical button
  - platform: gpio
    id: right_button
    name: "${device_name} right button"
    pin:
      number: 27
      inverted: true
    icon: mdi:light-switch
    on_press:
      - switch.toggle: relay_2
